Perfomance review
mikolaaaaaaa/E-mall pull request #1
Opened 2024-08-29 18:55 UTC by mikolaaaaaaa

2024-09-14 05:23 UTC, vovan- requested changes

2024-09-14 05:23 UTC, vovan- commented on client/src/main/java/by/mikola/client/config/KafkaTopicConfig.java
> +    public NewTopic topic1() {
orderTopic() instead of topoic1()?

2024-09-14 05:23 UTC, vovan- commented on client/src/main/java/by/mikola/client/config/KafkaConsumerConfig.java
> +    @Value(value = "${spring.kafka.bootstrap-servers}")
Instead of @Value it is better to create one common configuration properties DTO and mark it as @ConfigurationProperties, then inject it here and in other places

2024-09-14 05:23 UTC, vovan- commented on client/src/main/resources/application.yaml
> +      auto-offset-reset: earliest
in the task requirement "exactly once" message delivery should be implemented, here we use earliest offset reset, could you clarify for what purpose?

2024-09-14 05:23 UTC, vovan- commented on kube/client-service-deployment.yaml
> +    kompose.cmd: kompose convert
I see https://kompose.io/ was used for conversion of docker compose to kubernetes resources.
It would be great for you to also learn how to write kubernetes resource yaml definition files by your own

2024-09-14 05:23 UTC, vovan- commented on kube/deploy.sh
> +kubectl apply -f namespace.yaml,e-mall-db-service.yaml,mongo-service.yaml,zookeeper-service.yaml,kafka-service.yaml,eureka-server-service.yaml,order-service-service.yaml,client-service-service.yaml,e
Do these configurations require particular order? 
In kubectl it is possible to specify a folder to apply to avoid listing each and every file in a command

2024-09-14 05:23 UTC, vovan- commented on kube/e-mall-db-deployment.yaml
> +          imagePullPolicy: Never
Btw why it is decided here to use Never image pull policy?

2024-09-14 05:23 UTC, vovan- commented on kube/eureka-server-deployment.yaml
> +        - image: eureka-server-image
Kubernetes has its own service locator, do we really need eureka here if so for which purpose?

2024-09-14 05:23 UTC, vovan- commented on order/src/main/java/by/mikola/order/config/KafkaConsumerConfig.java
> +public class KafkaConsumerConfig {
Could you please clarify the requirement of "Exactly once" message delivery?

2024-09-14 05:23 UTC, vovan- commented on order/src/main/resources/application.yaml
> +      password: password
this and any other sensitive params should probably come from Docker/Kubernetes secrets as e.g. env variable and consumed in the service instead of hardcoding passwords in the code

2024-09-14 05:25 UTC, vovan- commented on order/src/test/java/by/mikola/order/OrderServiceImplTest.java
> +//    @Test
I see test containers are not yet used, are you going to add them,?

2024-09-26 11:43 UTC, mikolaaaaaaa commented on client/src/main/java/by/mikola/client/config/KafkaTopicConfig.java
> +    public NewTopic topic1() {
yes, corrected

2024-09-26 11:47 UTC, mikolaaaaaaa commented on client/src/main/java/by/mikola/client/config/KafkaConsumerConfig.java
> +    @Value(value = "${spring.kafka.bootstrap-servers}")
implemented

2024-09-26 11:50 UTC, mikolaaaaaaa commented on client/src/main/resources/application.yaml
> +      auto-offset-reset: earliest
At that point, the goal was just to add kafka “to make it work”. The “exactly once” requirement was not implemented

Now implemented.

2024-09-26 11:55 UTC, mikolaaaaaaa commented on kube/client-service-deployment.yaml
> +    kompose.cmd: kompose convert
Yes, my configurations didn't work and I tried to implement it in various ways)

I've now read a couple of manuals and refactored the deployment files

2024-09-26 11:56 UTC, mikolaaaaaaa commented on kube/deploy.sh
> +kubectl apply -f namespace.yaml,e-mall-db-service.yaml,mongo-service.yaml,zookeeper-service.yaml,kafka-service.yaml,eureka-server-service.yaml,order-service-service.yaml,client-service-service.yaml,e
refactored

2024-09-26 11:57 UTC, mikolaaaaaaa commented on kube/e-mall-db-deployment.yaml
> +          imagePullPolicy: Never
Corrected.
Now the “Never” policy is only for my containers

2024-09-26 11:58 UTC, mikolaaaaaaa commented on kube/eureka-server-deployment.yaml
> +        - image: eureka-server-image
Yes, that's right, there's no need for a eureka deployment

2024-09-26 12:01 UTC, mikolaaaaaaa commented on order/src/main/java/by/mikola/order/config/KafkaConsumerConfig.java
> +public class KafkaConsumerConfig {
Yes

I explored two options

-With configuration (ConsumerConfig.ENABLE_IDEMPOTENCE_CONFIG, true)

-With KafkaTransactionManager

I decided on the first way

2024-09-26 12:01 UTC, mikolaaaaaaa commented on order/src/main/resources/application.yaml
> +      password: password
implemented with .evn file for docker-compose and with configMap for k8s

2024-09-26 12:02 UTC, mikolaaaaaaa commented on order/src/test/java/by/mikola/order/OrderServiceImplTest.java
> +//    @Test
These were old tests, integration tests were not implemented at the time of the review

They are now)

2024-09-26 13:26 UTC, vovan- commented on order/src/main/java/by/mikola/order/config/KafkaConsumerConfig.java
> +public class KafkaConsumerConfig {
but wait your change relate only to producer, hence producer won't produce duplicate events(hopefully), so producer is covered, but now consumer can consume the same message twice e.g. in case of networking issues, e.g. it has already consumed the message(stored it to the DB) but failed to commit offset

2024-11-05 15:05 UTC, vovan- approved these changes

2024-12-12 13:39 UTC, merged